"use client"
import './globals.css';
import NavBar from './components/navBar';
import { Inter } from 'next/font/google';
import { useEffect, useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Time = {
  datetime: string;
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  const fetchData = async () => {
    const res = await fetch('http://worldtimeapi.org/api/timezone/America/Costa_Rica');
    const data: Time = await res.json();
    console.log(data);
    return data;
  };

  const [timeData, setTimeData] = useState<Time | null>(null);
  useEffect(() => {
    fetchData()
      .then((data) => {
        setTimeData(data);
      })
      .catch((error) => {
        console.error(error);
      });
  }, []);

  //format date and time
  const formatTime = (datetime: string) => {
    const date = new Date(datetime);
    const formattedDate = date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
    const formattedTime = date.toLocaleTimeString('en-US', {
      hour: 'numeric',
      minute: 'numeric',
      hour12: true,
    });

    return `${formattedDate} ${formattedTime}`;
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
        {timeData && <h3>{formatTime(timeData.datetime)}</h3>}
      </body>
    </html>
  );
}
